# Buildpack API version
api = "0.2"

# Buildpack ID and metadata
[buildpack]
id = "com.section31.buildpacks.smoketest"
version = "0.0.1"
name = "Smoketest Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"